# Generated by Django 5.2.7 on 2025-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_price_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="дата последнего уведомления по курсу",
            ),
        ),
    ]
